### ISSUE TITLE
unhandled error event log message

### ISSUE THREAD

**Issue by ZaleskiR** [dowjones/distribucache#4]
[distribucache] (prod:staticTextAPI) error from an unhandled `error` event:
 PopulateError: failed to populate key "centralbanks"; cause: timed out after 30000ms
    at null._onTimeout (/home/servo/node_modules/distribucache/lib/util.js:37:8)
    at Timer.listOnTimeout [as ontimeout] (timers.js:121:15)

Why is this reporting an error is unhandled?

**Comment by nemtsov** [comment]
When you create a new cache client (`var cacheClient = distribucache.createClient()`) you can choose to listen to `error` events via:

```js
cacheClient.on('error', function handler(err) {
  /* ... */ 
});
```

If you do not add an error handler, `distribucache` will report the error as `unhandled`. [Here's the code that implements that logic](https://github.com/dowjones/distribucache/blob/58797ca93957f907c82cfb3f970a76d557477802/lib/CacheClient.js#L132).
